# pubspec.yaml

name: mahargoyk
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ★★★ 日本語化対応のために追加 ★★★
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  cloud_firestore: ^4.9.1
  js: ^0.7.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  flutter_polyline_points: ^2.0.0
  http: ^1.2.1
  html: ^0.15.4
  flutter_tts: ^4.0.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.1.0
  provider: ^6.1.2 # 状態管理のために追加
  web: ^0.5.1
  # ★★★ バージョン競合を解決するために修正 ★★★
  intl: ^0.20.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/gtfs/
